name: Deploy to Harbor Registry

on:
  push:
    tags:
      - '*' # trigger only on version tags

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: HARBOR 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.zatto-lab.cloud -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t harbor.zatto-lab.cloud/topsky/napi:${{ github.ref_name }} .

      - name: Push to Harbor
        run: |
          docker push harbor.zatto-lab.cloud/topsky/napi:${{ github.ref_name }}
