name: Update ArgoCD Manifest Repo

on:
  push:
    tags:
      - '*'  # Trigger only on version tags

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: HARBOR

    steps:
      - name: Checkout source repo (n-api)
        uses: actions/checkout@v3

      - name: Extract tag
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Harbor
        run: echo "${HARBOR_PASSWORD}" | docker login harbor.zatto-lab.cloud -u "${HARBOR_USERNAME}" --password-stdin
        env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and Push Docker image
        working-directory: n-api
        run: |
          docker buildx build \
            --load \
            --build-arg MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            --build-arg NEWSKY_API_KEY="${{ secrets.NEWSKY_API_KEY }}" \
            --build-arg RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}" \
            -t harbor.zatto-lab.cloud/napi/napi:${{ env.TAG }} \
            .
          docker push harbor.zatto-lab.cloud/napi/napi:${{ env.TAG }}

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Create napi-secrets in K8s
        run: |
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl delete secret napi-secrets -n napi --ignore-not-found
          kubectl create secret generic napi-secrets \
            --from-literal=MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            --from-literal=NEWSKY_API_KEY="${{ secrets.NEWSKY_API_KEY }}" \
            --from-literal=RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}" \
            -n napi

      - name: Checkout argo-manifest repo
        uses: actions/checkout@v3
        with:
          repository: laszewskimariusz/argo-manifest
          token: ${{ secrets.GH_PAT }}
          path: argo-manifest

      - name: Update manifest with new image tag
        run: |
          sed -i "s|image: harbor.zatto-lab.cloud/napi/napi:.*|image: harbor.zatto-lab.cloud/napi/napi:${TAG}|" argo-manifest/apps/napi/deployment.yaml

      - name: Commit and push update to argo-manifest
        run: |
          cd argo-manifest
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "ci: update napi image to tag ${TAG}"
          git push
