name: Deploy to Harbor Registry

on:
  push:
    tags:
      - '*' # trigger only on version tags

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: HARBOR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Harbor
        run: echo "${HARBOR_PASSWORD}" | docker login harbor.zatto-lab.cloud -u "${HARBOR_USERNAME}" --password-stdin
        env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Docker image with Buildx
        working-directory: n-api
        run: |
          docker buildx build \
            --load \
            --build-arg MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            --build-arg NEWSKY_API_KEY="${{ secrets.NEWSKY_API_KEY }}" \
            -t harbor.zatto-lab.cloud/topsky/napi:${{ github.ref_name }} \
            .

      - name: Push Docker image
        working-directory: n-api
        run: docker push harbor.zatto-lab.cloud/topsky/napi:${{ github.ref_name }}
